local addonName, NS = ...   -- luacheck: ignore addonName

-- The known-pack manifest for the Sunn - Viewport Art adapter: what the OFFICIAL packs contain,
-- recorded here so the feature does not depend on their registration having run.
--
-- ── Why a list, when modules/SunnArt.lua discovers themes properly ──────────────
--
-- Discovery from the packs' own registration is still the primary mechanism and always wins; this
-- table is a fallback with one job. Every official pack TOC carries `## Dependencies: SunnArt`, and
-- the client enforces that before a single line of Lua runs — so if SunnArt is disabled, or stops
-- loading on a future patch, no pack registers anything and the whole feature goes silent. The
-- textures are unaffected: they are ordinary files under `Interface\Addons\`, and drawing one needs
-- no Sunn code at all. Only the KNOWLEDGE of what exists is lost, and that is what this restores.
--
-- Sunn - Viewport Art has not been updated since 2024-08 (`## Interface: … 110002`, five majors
-- behind at the time of writing), so "SunnArt stops loading" is the expected end state rather than
-- a hypothetical. If it is ever revived, this table quietly stops mattering — live registration
-- already takes precedence per theme.
--
-- Nothing is redistributed here either. This is a list of file names and sizes, not art: a row is
-- only ever offered when the pack's own folder is actually installed on the player's disk.
--
-- ── The one thing registration never provides ──────────────────────────────────
--
-- `w`/`h` are MEASURED from the section files, and they are the reason this table is consulted even
-- when discovery worked. SunnArt hard-codes a 2:1 aspect for everything (`SunnArt_Core.lua:259`,
-- `h = w * scale / 2`) and most sections are indeed 512x256 — but eight official themes are not.
-- Five are square 512x512 (Pack 6's Fractal, StreamBlue and StreamRed; Pack 9's Wrath and
-- Frostrock) and three are 1024 wide. Those are drawn squashed by SunnArt itself; measuring them
-- here is what lets this addon draw them at the shape they were authored at. Themes absent from
-- this table still fall back to the declared `S.SECTION_W`/`S.SECTION_H`.
--
-- `sections` is measured too — counted from the files present, not taken from the pack's
-- declaration — because a count that disagrees with what is installed would draw a section that
-- does not exist. The generator warns when the two differ; at the time of writing none do.
--
-- `overlap` is the pack's declared transparent band, as a PERCENTAGE, exactly as it appears in the
-- pack file. It is omitted when zero. See modules/SunnArt.lua ▸ *What `overlap` actually is*.
--
-- EVERY ROW BELOW IS GENERATED by `tools/sunn/build_manifest.py` from an installation that has the
-- packs. Do not hand-edit them. Unlike the artwork catalog this cannot be rebuilt from a clean
-- clone — its input is somebody's WoW folder — which is why the output is committed and the script
-- takes an explicit `--addons` path. Staleness is bounded and quiet: a stale row is only ever read
-- when live registration is absent, and live registration always wins.
NS.SunnArtPacks = {
  -- BEGIN GENERATED MANIFEST (tools/sunn/build_manifest.py) -- do not edit by hand
  ["SunnArtPack10\\wc3_decorative-"] = { name = "Warcraft III - Decorative", sections = 4, w = 512, h = 256 },
  ["SunnArtPack10\\wc3_horde-"] = { name = "Warcraft III - Horde", sections = 2, w = 1024, h = 256, overlap = 28.516 },
  ["SunnArtPack10\\wc3_human_ui2-"] = { name = "Warcraft III - Human UI", sections = 4, w = 512, h = 256, overlap = 29.687 },
  ["SunnArtPack10\\wc3_nelf_ui-"] = { name = "Warcraft III - Night Elf UI", sections = 4, w = 512, h = 256, overlap = 29.687 },
  ["SunnArtPack10\\wc3_orc_ui-"] = { name = "Warcraft III - Orc UI", sections = 4, w = 512, h = 256, overlap = 29.687 },
  ["SunnArtPack10\\wc3_undead_ui-"] = { name = "Warcraft III - Undead UI", sections = 4, w = 512, h = 256, overlap = 29.687 },
  ["SunnArtPack11\\cata2-"] = { name = "Cataclysm 2", sections = 4, w = 512, h = 256 },
  ["SunnArtPack11\\catabottom"] = { name = "Cataclysm (Bottom)", sections = 2, w = 1024, h = 256, overlap = 31.8 },
  ["SunnArtPack11\\cataside"] = { name = "Cataclysm (Sides)", sections = 1, w = 1024, h = 128 },
  ["SunnArtPack11\\deathwing"] = { name = "Deathwing", sections = 4, w = 512, h = 256 },
  ["SunnArtPack11\\goblin"] = { name = "Goblin", sections = 4, w = 512, h = 256 },
  ["SunnArtPack11\\worgen"] = { name = "Worgen", sections = 4, w = 512, h = 256 },
  ["SunnArtPack11\\worgen2"] = { name = "Worgen 2", sections = 4, w = 512, h = 256 },
  ["SunnArtPack1\\green"] = { name = "Green", sections = 3, w = 512, h = 256 },
  ["SunnArtPack1\\grey"] = { name = "Grey", sections = 3, w = 512, h = 256 },
  ["SunnArtPack1\\orange"] = { name = "Orange", sections = 3, w = 512, h = 256 },
  ["SunnArtPack1\\silver"] = { name = "Silver", sections = 3, w = 512, h = 256 },
  ["SunnArtPack2\\blackrock"] = { name = "Blackrock", sections = 3, w = 512, h = 256 },
  ["SunnArtPack2\\blueglow"] = { name = "Blue Glow", sections = 3, w = 512, h = 256 },
  ["SunnArtPack2\\burningcrusade"] = { name = "Burning Crusade", sections = 3, w = 512, h = 256 },
  ["SunnArtPack2\\scarab"] = { name = "Scarab", sections = 3, w = 512, h = 256 },
  ["SunnArtPack2\\temporal"] = { name = "Temporal", sections = 3, w = 512, h = 256 },
  ["SunnArtPack3\\dwarven"] = { name = "Dwarven", sections = 3, w = 512, h = 256 },
  ["SunnArtPack3\\elven"] = { name = "Elven", sections = 3, w = 512, h = 256 },
  ["SunnArtPack3\\granite"] = { name = "Granite", sections = 3, w = 512, h = 256 },
  ["SunnArtPack3\\illidan"] = { name = "Illidan", sections = 3, w = 512, h = 256 },
  ["SunnArtPack3\\tech"] = { name = "Tech", sections = 3, w = 512, h = 256 },
  ["SunnArtPack3\\wooden"] = { name = "Wooden", sections = 3, w = 512, h = 256 },
  ["SunnArtPack4\\emblem"] = { name = "Emblem", sections = 3, w = 512, h = 256 },
  ["SunnArtPack4\\horde"] = { name = "Horde", sections = 3, w = 512, h = 256 },
  ["SunnArtPack4\\scraped"] = { name = "Scraped", sections = 3, w = 512, h = 256 },
  ["SunnArtPack4\\spiked"] = { name = "Spiked", sections = 3, w = 512, h = 256 },
  ["SunnArtPack5\\console"] = { name = "Console", sections = 3, w = 512, h = 256 },
  ["SunnArtPack5\\frozen"] = { name = "Frozen", sections = 3, w = 512, h = 256 },
  ["SunnArtPack5\\icymail"] = { name = "Icy Mail", sections = 3, w = 512, h = 256 },
  ["SunnArtPack5\\leaves"] = { name = "Leaves", sections = 3, w = 512, h = 256 },
  ["SunnArtPack5\\purple"] = { name = "Purple", sections = 3, w = 512, h = 256 },
  ["SunnArtPack5\\purpleglow"] = { name = "Purple Glow", sections = 3, w = 512, h = 256 },
  ["SunnArtPack5\\redglow"] = { name = "Red Glow", sections = 3, w = 512, h = 256 },
  ["SunnArtPack5\\starburst"] = { name = "Starburst", sections = 3, w = 512, h = 256 },
  ["SunnArtPack6\\finwe"] = { name = "Finwe", sections = 3, w = 512, h = 256 },
  ["SunnArtPack6\\fractal"] = { name = "Fractal", sections = 3, w = 512, h = 512 },
  ["SunnArtPack6\\frostspire"] = { name = "Frost Spire", sections = 3, w = 512, h = 256 },
  ["SunnArtPack6\\nutribe"] = { name = "Nutribe", sections = 3, w = 512, h = 256 },
  ["SunnArtPack6\\streamblue"] = { name = "StreamBlue", sections = 3, w = 512, h = 512 },
  ["SunnArtPack6\\streamred"] = { name = "StreamRed", sections = 3, w = 512, h = 512 },
  ["SunnArtPack7\\alteracalliance"] = { name = "Alterac Valley (A)", sections = 3, w = 512, h = 256 },
  ["SunnArtPack7\\draeneifemale"] = { name = "Draenei 1", sections = 3, w = 512, h = 256 },
  ["SunnArtPack7\\draeneimale"] = { name = "Draenei 2", sections = 3, w = 512, h = 256 },
  ["SunnArtPack7\\dwarfmale"] = { name = "Dwarf 1", sections = 3, w = 512, h = 256 },
  ["SunnArtPack7\\dwarfmale2"] = { name = "Dwarf 2", sections = 3, w = 512, h = 256 },
  ["SunnArtPack7\\dwarfmale3"] = { name = "Dwarf 3", sections = 3, w = 512, h = 256 },
  ["SunnArtPack7\\dwarfmale4"] = { name = "Dwarf 4", sections = 3, w = 512, h = 256 },
  ["SunnArtPack7\\gnomefemale"] = { name = "Gnome 1", sections = 3, w = 512, h = 256 },
  ["SunnArtPack7\\gnomemale"] = { name = "Gnome 2", sections = 3, w = 512, h = 256 },
  ["SunnArtPack7\\humanfemale"] = { name = "Human 1", sections = 3, w = 512, h = 256 },
  ["SunnArtPack7\\humanfemale2"] = { name = "Human 2", sections = 3, w = 512, h = 256 },
  ["SunnArtPack7\\nightelf"] = { name = "Night Elf 1", sections = 3, w = 512, h = 256 },
  ["SunnArtPack7\\nightelffemale"] = { name = "Night Elf 2", sections = 3, w = 512, h = 256 },
  ["SunnArtPack7\\nightelffemale2"] = { name = "Night Elf 3", sections = 3, w = 512, h = 256 },
  ["SunnArtPack7\\nightelfmale"] = { name = "Night Elf 4", sections = 3, w = 512, h = 256 },
  ["SunnArtPack7\\stormwind"] = { name = "Stormwind", sections = 3, w = 512, h = 256 },
  ["SunnArtPack8\\alterachorde"] = { name = "Alterac Valley (H)", sections = 3, w = 512, h = 256 },
  ["SunnArtPack8\\bloodelffemale"] = { name = "Blood Elf 1", sections = 3, w = 512, h = 256 },
  ["SunnArtPack8\\orcfemale"] = { name = "Orc 1", sections = 3, w = 512, h = 256 },
  ["SunnArtPack8\\orcmale"] = { name = "Orc 2", sections = 3, w = 512, h = 256 },
  ["SunnArtPack8\\orcmale2"] = { name = "Orc 3", sections = 3, w = 512, h = 256 },
  ["SunnArtPack8\\orcmale3"] = { name = "Orc 4", sections = 3, w = 512, h = 256 },
  ["SunnArtPack8\\taurenfemale"] = { name = "Tauren 1", sections = 3, w = 512, h = 256 },
  ["SunnArtPack8\\taurenmale"] = { name = "Tauren 2", sections = 3, w = 512, h = 256 },
  ["SunnArtPack8\\trollfemalepriest"] = { name = "Troll 1", sections = 3, w = 512, h = 256 },
  ["SunnArtPack8\\trollmale"] = { name = "Troll 2", sections = 3, w = 512, h = 256 },
  ["SunnArtPack8\\undeadfemale"] = { name = "Undead 1", sections = 3, w = 512, h = 256 },
  ["SunnArtPack8\\undeadfemale2"] = { name = "Undead 2", sections = 3, w = 512, h = 256 },
  ["SunnArtPack8\\undeadmalerogue"] = { name = "Undead 3", sections = 3, w = 512, h = 256 },
  ["SunnArtPack8\\undeadwarlock"] = { name = "Undead 4", sections = 3, w = 512, h = 256 },
  ["SunnArtPack9\\Wrath"] = { name = "Wrath", sections = 3, w = 512, h = 512 },
  ["SunnArtPack9\\arthas"] = { name = "Arthas", sections = 3, w = 512, h = 256 },
  ["SunnArtPack9\\blacktemple"] = { name = "Black Temple", sections = 3, w = 512, h = 256 },
  ["SunnArtPack9\\deathknight"] = { name = "Deathknight", sections = 3, w = 512, h = 256 },
  ["SunnArtPack9\\frostrock"] = { name = "Frostrock", sections = 3, w = 512, h = 512 },
  ["SunnArtPack9\\naaru"] = { name = "Naaru", sections = 3, w = 512, h = 256 },
  ["SunnArtPack9\\sunwell"] = { name = "Sunwell", sections = 3, w = 512, h = 256 },
  ["SunnArtPack9\\utgarde"] = { name = "Utgarde", sections = 3, w = 512, h = 256 },
  ["SunnArt\\forsaken"] = { name = "Forsaken", sections = 3, w = 512, h = 256 },
  ["SunnArt\\rogue"] = { name = "Rogue", sections = 3, w = 512, h = 256 },
  ["SunnArt\\royal"] = { name = "Royal", sections = 3, w = 512, h = 256 },
  ["SunnArt\\tribal"] = { name = "Tribal", sections = 3, w = 512, h = 256 },
  -- END GENERATED MANIFEST
}
