-- tests/test_vendor_sync.lua — the vendored-payload gate. The implementation now lives once, in
-- `tests/_kit/vendor_sync.lua`, vendored from LibKa0s alongside the payload it checks; this file is
-- the consumer-side registration and nothing else. The ~140 hand-copied lines that used to live here
-- were the same bytes in eight repos, which is exactly the duplication the kit exists to end.
--
-- WHAT IT CHECKS: that `libs/LibKa0s/` and `tests/_kit/` in this repo are exactly
-- what the LibKa0s repo published at the tag THIS REPO'S CLAUDE.md says it bundles.
--
-- THE PROVENANCE LINE IS AN INPUT, NOT A CONSTANT. It is read out of CLAUDE.md
-- rather than hardcoded: a provenance line and a vendored payload that disagree
-- is precisely the drift this file exists to catch, so the claim has to be the
-- thing under test. Bump the line and the bytes in the same commit.
--
-- ONE NORMALIZATION, AND ONLY ONE: `git show` hands back the stored blob, which
-- is always LF, while the working tree's line endings are whatever the CHECKOUT
-- produced. This repo's `.gitattributes` pins the tree CRLF — `* text=auto
-- eol=crlf`, the client-bound pin of `line-endings-§2` — so the two sides differ
-- by representation on every checkout, by policy rather than by accident, and the
-- strip is load-bearing rather than defensive. It stays unconditional: a straggler
-- written by a tool that bypassed git's filters is LF in the same tree, and the
-- comparison must not care which. CR is stripped from the working-tree side so the file is compared to
-- the blob it round-trips to, rather than failing on one maintainer's machine and
-- passing on another's. Nothing else is normalized — a real
-- fork in content still fails. That strip lives in `tests/_kit/vendor_sync.lua`;
-- it is carried in verbatim from AbsorbTracker/tests/test_vendor_sync.lua and it
-- is the behavior in use. `testing-§11`'s no-normalization MUST is scoped to the
-- library-side pair, where both sides are working-tree directories in one
-- checkout — not to this blob-versus-worktree comparison.
--
-- WHEN THE SIBLING CHECKOUT IS ABSENT the kit reports SKIP with a reason naming
-- the missing checkout, and the run's exit code stays 0. It never reports PASS
-- for a comparison that did not run.
--
-- The case names are the kit's own defaults, so no `pairs` override is needed.
-- Kit revision 9 renamed the first of the two — it now says CLAUDE.md rather
-- than the README — which is the only part of that revision visible outside
-- `tests/_kit/`, and `docs/test-cases.md` was regenerated in the same commit.
-- The default provenance pattern `[Bb]undles %[LibKa0s%]%b() (v[%d%.]+)` matches
-- this repo's line in `CLAUDE.md`, and the default `provenanceFile` is already
-- `CLAUDE.md`, so neither opt is overridden here.

local VendorSync = dofile("tests/_kit/vendor_sync.lua")

VendorSync.register(_G.PM_TEST, {})
